######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 10 00:14:19 2013
######################################################################

QT       += core
QT       += network

QT       += core gui


TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += object.h
SOURCES += main.cpp object.cpp
